Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/scratchattach/session.py", line 546, in login
    session_id = str(re.search('"(.*)"', request.headers["Set-Cookie"]).group())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weather.py", line 13, in <module>
    session = scratch3.login(r[0], r[1])
  File "/home/ec2-user/.local/lib/python3.7/site-packages/scratchattach/session.py", line 548, in login
    raise exceptions.LoginFailure("Either the provided authentication data is wrong or your network is banned from Scratch.\n\nIf you're using an online IDE (like replit.com) Scratch possibly banned its IP adress. In this case, try logging in with your session id: https://github.com/TimMcCool/scratchattach/wiki#logging-in")
scratchattach.exceptions.LoginFailure: Either the provided authentication data is wrong or your network is banned from Scratch.

If you're using an online IDE (like replit.com) Scratch possibly banned its IP adress. In this case, try logging in with your session id: https://github.com/TimMcCool/scratchattach/wiki#logging-in
